name: tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: GoLang Test
        uses: n8maninger/action-golang-test@v1